import {
	Box,
	Button,
	Card,
	CardContent,
	CardHeader,
	CardMedia,
	Container,
	Divider,
	Grid,
	Paper,
	Table,
	TableBody,
	TableCell,
	TableRow,
	Typography,
} from '@mui/material'
import { graphql, Link } from 'gatsby'
import { StaticImage } from 'gatsby-plugin-image'
import React, { useEffect, useState } from 'react'
import Layout from '../components/Organisms/Layout'
import { ArticleModel, ArticleResponse } from '../models/ArticleModel'

const AboutEmma: React.FunctionComponent<{ data: any }> = ({ data }) => {
	const [articles, articlesSet] = useState<ArticleModel[]>([])
	const [selectedArticle, selectedArticleSet] = useState<ArticleModel | null>(null)

	const handleClick = async (selectedItem: ArticleModel) => {
		selectedArticleSet(selectedItem)
	}

	useEffect(() => {
		let model = data.allNodeArticle.nodes as ArticleModel[]
		articlesSet(model)
		if (model.length > 0) {
			selectedArticleSet(model[0])
		}
	}, [])

	return (
		<Layout>
			<Container sx={{ minHeight: '80vh' }}>
				<h3>About EMMA</h3>
				<Typography variant='body1'>
					the content below was created using DSG - Deferred Static Generation and was generated by the first visit to
					the page
				</Typography>
				<hr></hr>
				<Grid container spacing={2}>
					<Grid item xs={2}>
						<Card
							sx={{
								bgcolor: 'whitesmoke',
							}}>
							{articles.map((article) => (
								<Typography key={article.id} sx={{ textAlign: 'center' }}>
									<Button
										sx={{ width: '100%' }}
										onClick={() => {
											handleClick(article)
										}}>
										{article.title}
									</Button>
									<Divider />
								</Typography>
							))}
						</Card>
					</Grid>
					<Grid item xs={8}>
						<Box sx={{ alignItems: 'center' }}>
							{selectedArticle && (
								<Box>
									<Typography>{selectedArticle.body.summary}</Typography>
									<div dangerouslySetInnerHTML={{ __html: selectedArticle.body.processed }}></div>
								</Box>
							)}
						</Box>
					</Grid>
					<Grid item xs={2}>
						<Card sx={{ fontSize: 'smaller', textAlign: 'center' }}>
							<CardHeader title='Watch a Video About EMMA'></CardHeader>
							<CardContent>
								<Typography>
									<StaticImage src='../assets/images/video-icon.png' alt='Watch a Video About EMMA' />
								</Typography>
								<Typography variant='body2'>
									<a href='https://wwwq4.msrb.org/EducationCenter/video-player.aspx?section=0&video=0&hash=096d6e76ba'>
										Watch a video to learn how EMMA can help investors.
									</a>
								</Typography>
							</CardContent>
							<Box></Box>
						</Card>
						<Card sx={{ fontSize: 'smaller', textAlign: 'center', marginTop: '2px' }}>
							<CardHeader title='Getting Started with EMMA'></CardHeader>
							<CardContent>
								<Typography>
									<StaticImage src='../assets/images/www-doc.png' alt='Getting Started with EMMA' />
								</Typography>
								<Typography variant='body2'>
									<a href='https://emmaq1.msrb.org/Home/GettingStarted'>New to EMMA? Find out more.</a>
								</Typography>
							</CardContent>
							<Box></Box>
						</Card>
						<Card sx={{ fontSize: 'smaller', textAlign: 'center', marginTop: '2px' }}>
							<CardHeader title='Learn About MyEMMA Alerts'></CardHeader>
							<CardContent>
								<Typography>
									<StaticImage
										src='../assets/images/investor-alerts-icon.png'
										alt='Read how to receive email notifications about documents posted on EMMA.'
									/>
								</Typography>
								<Typography variant='body2'>
									<a href='http://www.msrb.org/msrb1/EMMA/pdfs/MyEMMA-Advantages.pdf'>
										Read how to receive email notifications about documents posted on EMMA.
									</a>
								</Typography>
							</CardContent>
							<Box></Box>
						</Card>
						<Card sx={{ fontSize: 'smaller', textAlign: 'center', marginTop: '2px' }}>
							<CardHeader title='Glossary of Terms'></CardHeader>
							<CardContent>
								<Typography>
									<StaticImage
										src='../assets/images/glossary-icon.png'
										alt="View the MSRB's industry-standard Glossary of Municipal Securities Terms."
									/>
								</Typography>
								<Typography variant='body2'>
									<a href='https://wwwq4.msrb.org/Glossary.aspx'>
										View the MSRB's industry-standard Glossary of Municipal Securities Terms.
									</a>
								</Typography>
							</CardContent>
							<Box></Box>
						</Card>
					</Grid>
				</Grid>
			</Container>

			{/* {articles && articles.length > 0 && (
						<Table>
							<TableBody>
								{articles.map((rule) => (
									<TableRow key={rule.id}>
										<TableCell>
											<Link to={rule.path.alias}>{rule.title}</Link>
										</TableCell>
										<TableCell>
											<Link to={rule.path.alias}>{rule.body.summary}</Link>
										</TableCell>
									</TableRow>
								))}
							</TableBody>
						</Table>
					)} */}
		</Layout>
	)
}
export const query = graphql`
	query {
		allNodeArticle(filter: { path: { alias: { glob: "*/AboutEmma/*" } } }, sort: { fields: title, order: ASC }) {
			nodes {
				id
				title
				path {
					alias
				}
				body {
					summary
					processed
				}
			}
		}
	}
`
export async function config() {
	// Optionally use GraphQL here
	return () => {
		return {
			defer: true,
		}
	}
}
export default AboutEmma
