import Layout from '../components/Organisms/Layout'
import { graphql, Link } from 'gatsby'
import { ArticleResponse } from '../models/ArticleModel'
import React from 'react'
import { Container, Typography } from '@mui/material'

const Article: React.FunctionComponent<{ data: ArticleResponse }> = ({ data }) => {
	const article = data.nodeArticle

	return (
		<Layout>
			<Container>
				<Link to='/AboutEmma'>&laquo; back</Link>
				<h2>{article.title}</h2>
				<Typography variant='body2'>the content below is static and was generated by a build</Typography>
				<hr></hr>

				<div style={{ minHeight: '25em' }}>
					<div dangerouslySetInnerHTML={{ __html: article.body.processed }}></div>
				</div>
			</Container>
		</Layout>
	)
}

export const query = graphql`
	query ($ArticleId: String!) {
		nodeArticle(id: { eq: $ArticleId }) {
			id
			title
			body {
				processed
			}
		}
	}
`

export default Article
